module.exports = async () => {
  return [
    {
      first_name: 'Matei',
      last_name: 'Marinescu',
      birthday: new Date("2005-04-02"),
      email: 'mateimarinescu@gmail.com',
      category:'I',
    },
    {
      first_name: 'Andreea',
      last_name: 'Andreescu',
      birthday: new Date("2006-03-08"),
      email: 'aandreescu@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Tudor',
      last_name: 'Ursache',
      birthday: new Date("2008-12-12"),
      email: 'ursachetdr@gmail.com',
      category: 'Candidat de maestru',
    },
    {
      first_name: 'Florina',
      last_name: 'Baston',
      birthday: new Date("2006-08-14"),
      email: 'bastonemilia@gmail.com',
      category: '-',
    },
    {
      first_name: 'Simon',
      last_name: 'Vladescu',
      birthday: new Date("2005-10-07"),
      email: 'vldvld@gmail.com',
      category: 'III',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Andrei-Theodor',
      last_name: 'Dolana',
      birthday: new Date("1999-04-14"),
      email: 'dolanaandrei@ase.ro',
      category: 'Maestru FIDE',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
    {
      first_name: 'Maria-Alexandra',
      last_name: 'Popa',
      birthday: new Date("2010-09-15"),
      email: 'mapopa@gmail.com',
      category: 'II',
    },
  ];
};
